defaults: &defaults
  working_directory: ~/android_apk
  docker:
    - image: circleci/android:api-26-alpha

version: 2
jobs:
  rspec:
    - restore_cache: &restore_gradle_cache
        keys: 
          - bundle-v1-{{ checksum "Gemfile.lock" }}
    - run: bundle install --clean --path=vendor/bundle
    - save_cache:
        paths:
          - vendor/bundle
        key: bundle-v1-{{ checksum "Gemfile.lock" }}
    - run: bundle exec rspec spec

workflows:
  version: 2
  build:
    jobs:
      - rspec