name: Build and test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        task:
          - rubocop
          - rdoc
    timeout-minutes: 5
    name: "Execute ${{ matrix.task }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          bundler-cache: true
      - run: bundle exec rake ${{ matrix.task }}

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix: # Use as the parameter injection
        java-version:
          - 11
        buildtools-version:
          - 35.0.1
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          bundler-cache: true
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
      - uses: ./.github/actions/setup-buildtools
        with:
          buildtools-version: ${{ matrix.buildtools-version }}
      - run: bundle exec rake specs
